✨ 演算子を追加可能に
ChenCMD/MC-Datapack-Utility pull request #15
Opened 2020-11-05 11:54 UTC by t5ugu

2020-11-05 14:15 UTC, ChenCMD requested changes
discordも参照してネ

2020-11-05 14:15 UTC, ChenCMD commented on src/commands/scoreOperation/types/ScoreTable.ts
> +    axiom: Array<Axiom>
```suggestion
    axiom: Axiom[]
```

2020-11-05 15:41 UTC, t5ugu reviewed
直してみました。初めての操作なので間違っていたりすればDiscordへ

2020-11-05 15:41 UTC, t5ugu commented on src/commands/scoreOperation/types/ScoreTable.ts
> +    latter: boolean
```suggestion
    former?: boolean
    op: '*=' | '/=' | '%=' | '+=' | '-=' | '='
    latter?: boolean
```

2020-11-05 15:41 UTC, t5ugu commented on src/commands/scoreOperation/types/ScoreTable.ts
> +                    latter: false
```suggestion
                    op: '*='
```

2020-11-05 15:41 UTC, t5ugu commented on src/commands/scoreOperation/types/ScoreTable.ts
> +                    latter: false
```suggestion
                    op: '/='
```

2020-11-05 15:41 UTC, t5ugu commented on src/commands/scoreOperation/types/ScoreTable.ts
> +                    latter: false
```suggestion
                    op: '%='
```

2020-11-05 15:41 UTC, t5ugu commented on src/commands/scoreOperation/types/ScoreTable.ts
> +                    latter: false
```suggestion
                    op: '+='
```

2020-11-05 15:41 UTC, t5ugu commented on src/commands/scoreOperation/types/ScoreTable.ts
> +                    latter: false
```suggestion
                    op: '-='
```

2020-11-06 07:03 UTC, ChenCMD approved these changes

2020-11-06 07:04 UTC, merged

2020-11-09 07:54 UTC, ChenCMD commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ChenCMD.mc-datapack-utility)
- [GitHub release](https://github.com/ChenCMD/MC-Datapack-Utility/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: