🎉 インデントと空行を入れるフォーマッター
ChenCMD/MC-Datapack-Utility pull request #34
Opened 2021-01-15 13:49 UTC by t5ugu

2021-02-21 05:18 UTC, t5ugu commented
他の開発もあるのは存じ上げておりますが、できればReviewを、添削をお願いします。

2021-02-27 02:10 UTC, ChenCMD requested changes

2021-02-27 02:10 UTC, ChenCMD commented on src/languages/McfunctionFormatter.ts
> +        }
ここutils/StringReader使ったほうがたぶん綺麗

2021-03-19 09:38 UTC, ChenCMD requested changes
StringReaderに[これ](https://github.com/SPYGlassMC/SPYGlass/blob/release/3.3.0/src/utils/StringReader.ts#L355-L365)追加して全体で一つのStringReaderを使いまわすようにしてね
あと、#35 がこのブランチをmergeして作られてるのでそっちをcloseしてこっちに統合して

2021-03-21 11:28 UTC, ChenCMD requested changes
何のためにStringReader.nextLine()増やさせたと思ってるの.....最初にテキスト全体を引数に入れてStringReader作成してそれ使って実装して

2021-03-23 11:13 UTC, t5ugu commented
vscode-languageserver-textdocumentからimportしたTextDocumentへ、vscodeからimportしたTextDocumentを当てはめるためにわざわざURIをtoString()していますが、contentだけ入れておいて後は空でも良かったのでしょうか。

2021-03-25 13:21 UTC, ChenCMD requested changes

2021-03-25 13:21 UTC, ChenCMD commented on package.json
> +					"default": true
defaultはfalseのほうがいい

2021-03-25 13:21 UTC, ChenCMD commented on package.nls.json
> +    "mcdutil.config.mcfFormatter.doInsertIMPDocument": "**Insert IMP-Doc**: When formatting a \".mcfunction\" document with Data-pack Helper Plus, insert IMP-Doc at the Beg of the file."
jaと文言が違くない？

2021-03-25 13:21 UTC, ChenCMD commented on src/utils/StringReader.ts
> +
これなら普通にVSCode側のをimportしてインスタンス生成してよさそう

2021-03-25 13:21 UTC, ChenCMD commented on src/languages/McfunctionFormatter.ts
> +        const rootPath = await getDatapackRoot(document.uri.fsPath);
uri.fsPathじゃなくてfileNameで良い気がする

2021-03-25 13:21 UTC, ChenCMD commented on src/languages/McfunctionFormatter.ts
> +            return delivery(`:${document.fileName.slice(document.fileName.lastIndexOf('\\\\')).replace('.mcfunction', '')}`);
そもそもundefinedなら無理にinsert動作をするべきではない

2021-03-25 13:21 UTC, ChenCMD commented on src/languages/McfunctionFormatter.ts
> +        }
ここのコードが冗長なので改善してね

2021-03-26 23:37 UTC, t5ugu commented
insertProtocolの戻り値に関して、配列はパフォーマンスや可読性が落ちますかね？

他の機能を増やせるように、いちおう配列を返していますが、よろしくなさそうであっても、私は別解を思いついてません。

配列を返す今の状態で満足していますが、万が一もあるのかなと思い、ここに置いておきます。

2021-03-27 00:03 UTC, t5ugu commented
reviewについていたメッセージに応えるようなcommit名にしておきました。
ですが今後のためにも、requestに応えるcommitは一括でおこなうのが良いのか聞いておきたいと思っています。

2021-03-29 18:08 UTC, ChenCMD requested changes
とりあえずmaster mergeしてください

2021-03-29 18:08 UTC, ChenCMD commented on src/languages/McfunctionFormatter.ts
> +
```suggestion
            }


```

2021-03-29 18:08 UTC, ChenCMD commented on src/languages/McfunctionFormatter.ts
> +
```suggestion

```

2021-03-29 18:08 UTC, ChenCMD commented on src/languages/McfunctionFormatter.ts
> +
```suggestion

```

2021-03-30 09:04 UTC, merged

2021-04-30 10:09 UTC, ChenCMD commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ChenCMD.mc-datapack-utility)
- [GitHub release](https://github.com/ChenCMD/MC-Datapack-Utility/releases/tag/untagged-17e966f5fcbaef425f98)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: