Revert "Revert "🎉 インデントと空行を入れるフォーマッター (#34)""
ChenCMD/MC-Datapack-Utility pull request #38
Opened 2021-04-07 04:49 UTC by t5ugu

This reverts commit 39c5731a0b5d349892068b465a47df6b669e168d.

2021-04-08 08:58 UTC, ChenCMD requested changes
改行コードがCRLFの場合を考えてなさそう、あとここに限った話ではないけどconfigのexportを外したいので引数に渡すなりそれ用の関数を作るなりしてMcfunctionFormatterクラスのフィールドに持たせてね

2021-04-08 08:58 UTC, ChenCMD commented on src/languages/McfunctionFormatter.ts
> +        return [...await this.insertProtocol(document), ...this.insertIndent(document, indent)];
ans的なTextEdit[]型の変数作って一関数毎にpushしたほうが可読性とか拡張するのが楽そう

2021-04-12 11:46 UTC, t5ugu commented
直前のコミット( e34aa9e1cfc403385be3e4d670a938712c7d229f )は、現時点ではIMP-Docを挿入しているとは言い難いこともあり、また名は体を表していた方がよいと感じたため、名称を変更したコミット。

2021-04-24 19:58 UTC, ChenCMD requested changes

2021-04-24 19:58 UTC, ChenCMD commented on src/extension.ts
> +        McfunctionFormatter.prototype.setConfig(config);
普通に生成したインスタンスのsetConfig呼び出さないと意味ない

2021-04-24 19:58 UTC, ChenCMD commented on src/languages/McfunctionFormatter.ts
> +    }
```suggestion
    constructor(private config: Config) { }
```

2021-04-24 19:58 UTC, ChenCMD commented on src/languages/McfunctionFormatter.ts
> +    }
```suggestion
    set config(config: Config): void {
        this.config = config;
    }
```

2021-04-24 19:58 UTC, ChenCMD commented on src/languages/McfunctionFormatter.ts
> +        return undefined;
ここはEarly Returnしたほうがインデント減らせてきれい

2021-04-24 19:58 UTC, ChenCMD commented on src/languages/McfunctionFormatter.ts
> +        })();
ここまでしてconstにする必要性ないと思う

2021-04-26 08:52 UTC, ChenCMD requested changes

2021-04-26 08:52 UTC, ChenCMD commented on src/extension.ts
> +        mcfunctionFormatter.cfg = config;
updateConfigの第2引数にcb: (config:Config) => void | Promise<void>を追加してformatterのconfigを適用した方が綺麗かな

2021-04-26 08:52 UTC, ChenCMD commented on src/languages/McfunctionFormatter.ts
> +    constructor(private config: Config) { }
引数名に_をprefixとして付けてsetterの方は普通にconfigにするべき

2021-04-29 06:12 UTC, ChenCMD requested changes

2021-04-29 06:12 UTC, ChenCMD commented on src/languages/McfunctionFormatter.ts
> +        if (this._config.mcfFormatter.doInsertIMPDocument === true) {
冗長

2021-04-29 06:12 UTC, ChenCMD commented on src/extension.ts
> +    disposable.push(workspace.onDidChangeConfiguration(updateConfig, { cb: () => mcfunctionFormatter.config = config }));
```suggestion
    disposable.push(workspace.onDidChangeConfiguration(event => updateConfig(event, cfg => {
        loadLocale(cfg.env.language, vscodeLanguage);
        mcfunctionFormatter.config = cfg;
    })));
```

2021-04-29 06:12 UTC, ChenCMD commented on src/extension.ts
>      }
```suggestion
async function updateConfig(event: ConfigurationChangeEvent, cb: (config: Config) => void | Promise<void>): Promise<void> {
    if (event.affectsConfiguration('mcdutil')) {
        config = constructConfig(workspace.getConfiguration('mcdutil'));
        await cb(config);
    }
```

2021-04-29 07:43 UTC, t5ugu commented
サジェストそのままコピペしましたが、念のためRe requestしました。

2021-04-29 19:31 UTC, ChenCMD requested changes

2021-04-29 19:31 UTC, ChenCMD commented on src/extension.ts
> +    })));
prefixに_を付けた変数は基本的に非使用を表現するものなので名前を変えるべき

2021-04-30 07:09 UTC, t5ugu commented on src/extension.ts
> +    })));
prefixの_は無い方が良いとのことですが、私はconfigという語を残したいなと思うので、newConfigなどいかがでしょうか？

2021-04-30 09:20 UTC, ChenCMD approved these changes

2021-04-30 09:21 UTC, merged

2021-04-30 10:09 UTC, ChenCMD commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ChenCMD.mc-datapack-utility)
- [GitHub release](https://github.com/ChenCMD/MC-Datapack-Utility/releases/tag/untagged-17e966f5fcbaef425f98)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: